### ISSUE TITLE
UWP plotview not showing until resizing

### ISSUE THREAD

**Issue by Swerfer** [oxyplot/oxyplot-xamarin#67] opened 2017-08-19 16:45 UTC
In my case I have 2 situations:

1 My app is in landscape: The plotview is showing
2 My app is in portrait: Plotview not showing until resizing (on PC) or rotate to landscape and back on phone.

If I, as a workaround, could force a SizeChanged event firing without user interaction just after setting the plotview's model, then I think the plotview will show.

**Comment by onelloyd** [comment] 2018-04-26 17:41
Hi Did you figure out a work around for this issue?

**Comment by Swerfer** [comment] 2018-04-26 18:53
No, and I also stopped developing my app so I don't use oxyplot anymore.

**Comment by objorke** [comment] 2019-10-20 19:26
Duplicate of #34

**Closed as completed by objorke** 2019-10-20 19:26 UTC
Labels: bug, UWP
