### ISSUE TITLE
Tons of errors on Resource.Designer.cs after adding OxyPlot to the project

### ISSUE THREAD

**Issue by rbasniak** [oxyplot/oxyplot-xamarin#43] opened 2016-10-14 02:54 UTC
These the steps to reproduce it:

1 - Create a new Blank App (`Xamarin.Forms.Portable`) on VS 2015 Update 3 (`Xamarin 4.2.0.703` and `Xamarin.Android 7.0.1.3`)

2 - On Nuget Package Manager update `Xamarin.Forms` to latest version (currently `v2.3.3.152-pre2`)

3 - Run the application to confirm that everything is working.

4 - Back to Nuget, add a referente of `OxyPlot.Xamarin.Forms` to both my projects (portable and droid). It installs `OxyPlot.Xamarin.Forms` and `OxyPlot.Xamarin.Android` version `1.0.0-unstable1983` and 'OxyPlot.Core`version`2015.1.708-alpha`)

5 - On my Droid project, in `MainActivity.cs` I add `OxyPlot.Xamarin.Forms.Platform.Android.PlotViewRenderer.Init();` after the call to `Forms.Init()`

6 - Now if I try to compile my application again I have ~150 errors on `Resource.Designer.cs`: 

![image](https://cloud.githubusercontent.com/assets/10734059/19374134/f2e482f0-919f-11e6-9cc3-67c57672cc23.png)

If I remove OxyPlot from the project, the errors go away and the application compiles again.

My target SDK versions are the following:

![image](https://cloud.githubusercontent.com/assets/10734059/19374150/168746d4-91a0-11e6-8578-c489a46f9925.png)

**Comment by hugoranito** [comment] 2016-10-20 17:08
hi @rbasniak 
same problem here. any solution for this?

**Comment by rbasniak** [comment] 2016-10-20 23:24
Hi @hugoranito, unfortunately not. Decided to put the project apart while this doesn't  get fixed, since it's the only decent and free charting library for Xamarin :(

**Comment by rafadorado** [comment] 2016-11-06 11:29
Same here :-(

**Comment by frost753** [comment] 2016-11-11 09:41
I have same problem, but temporary solution seems to be just comment out lines with errors in Resource.Designer.cs, project then can be build and charts are working.

**Comment by paulocinf** [comment] 2016-12-21 13:13
did anyone get to a solution? i'm having the same 151 errors

**Comment by objorke** [comment] 2016-12-22 20:36
sorry, I am not having time to look into this myself at the moment.

**Comment by JosephGarrone** [comment] 2017-01-04 04:50
This issue is being caused by the Nuget package version mismatches.

Check [the Nuget page for OxyPlot.Xamarin.Forms](https://www.nuget.org/packages/OxyPlot.Xamarin.Forms) and you will see it requires:

>OxyPlot.Core (= 1.0.0-unstable1983)

However that version does not exist in Nuget, as seen for [OxyPlot.Core](https://www.nuget.org/packages/OxyPlot.Core/)
>OxyPlot core... 1.0.0 (this version)

[This issue](https://github.com/oxyplot/oxyplot/issues/1041) is also related to this.

**Comment by j-monteiro** [comment] 2017-01-04 15:55
@JosephGarrone it does exist (but don't know were it is really xD). I was also confused when adding the nugets, but when i searched for pre release packages i found the "Oxyplot.Xamarin.Forms 1.0.0-unstable1983" (the one you've posted), i installed that package and the Oxyplot.Core 1.0.0-unstable1983 was automatically installed, the package manager did the job for me, just don't install the Oxyplot.Core 1.0.0 (if you have it installed, remove it and then install the "Oxyplot.Xamarin.Forms 1.0.0-unstable1983" again)

**Comment by JosephGarrone** [comment] 2017-01-04 23:02
@j-monteiro I just installed from the [MyGet Feed](https://www.myget.org/feed/oxyplot/package/nuget/OxyPlot.Core). You will notice in the versions listed there that there is no unstable1983, and if you look at [OxyPlot.Xamarin.Forms](https://www.myget.org/feed/oxyplot/package/nuget/OxyPlot.Xamarin.Forms), it is only up to unstable0680.

**Comment by j-monteiro** [comment] 2017-01-05 01:12
@JosephGarrone sorry if I'm not understanding the situation correctly. The thing is that I have the "Oxyplot.Core 1.0.0-unstable1983" in my project, with "OxyPlot.Xamarin.Forms 1.0.0-unstable1983"
<img width="353" alt="captura de ecra 2017-01-05 as 00 58 44" src="https://cloud.githubusercontent.com/assets/15830093/21665151/e00679ca-d2e2-11e6-8c8f-1dc446954594.png">

**Comment by JosephGarrone** [comment] 2017-01-05 01:13
@j-monteiro The issue is that whilst that might be the version you have installed, its not properly accessible via NuGet/MyGet due to mismatched versioning dependencies. And if you check my links, you will see that that version doesn't actually exist presently.

**Comment by j-monteiro** [comment] 2017-01-05 01:17
@JosephGarrone the MyGet link you've posted it's not opening here :s but yes, I can't find this version anywere, it was simply installed in conjunction whith the "OxyPlot.Xamarin.Forms 1.0.0-unstable1983" installation.

**Comment by JosephGarrone** [comment] 2017-01-05 02:05
Yeh I think it's only an issue for existing installs where NuGet fails to remove the existing packages :(.

Here are the relevant parts of the links:

![image](https://cloud.githubusercontent.com/assets/4310797/21666696/1a633fca-d33f-11e6-93fa-e9db570db551.png)
![image](https://cloud.githubusercontent.com/assets/4310797/21666716/365c0f5e-d33f-11e6-8c82-2e881911e236.png)
![image](https://cloud.githubusercontent.com/assets/4310797/21666722/41140d16-d33f-11e6-8414-b016f3d38a9d.png)

**Comment by objorke** [comment] 2017-01-08 17:57
Can you try again with OxyPlot.Xamarin.Forms.1.1.0-unstable0011 (nuget.org)
It seems to work from here

**Comment by objorke** [comment] 2017-01-08 17:57
@rbasniak can we close this issue?

**Comment by objorke** [comment] 2019-11-28 20:08
I suggest including oxyplot-xamarin as a git submodule instead. This should make it easier to debug issues like this. See #84

**Comment by objorke** [comment] 2019-11-28 20:08
Closed due to inactivity

**Closed as completed by objorke** 2019-11-28 20:08 UTC
Labels: bug, Android, high priority, Xamarin.Forms
